const items = [
  {
    id: "001",
    Chicken_item: "Butter chicken",
    weight: "1kg",
    price: "$400",
    img: "./1.jpeg",
    CoockedBy: "Piyush Kumar",
    rating: "1.4k",
  },
  {
    id: "002",
    Chicken_item: "Chilley chicken",
    weight: "500gm",
    price: "$300",
    img: "./2.jpeg",
    CoockedBy: "Abhishek sir",
    rating: "1.7k",
  },
  {
    id: "003",
    Chicken_item: "Butter Tandoor",
    weight: "1.5kg",
    price: "$700",
    img: "./3.webp",
    CoockedBy: "Arun kumar",
    rating: "1.00k",
  },
  {
    id: "004",
    Chicken_item: "chicken Kroma",
    weight: "600gm",
    price: "$600",
    img: "./4.jpeg",
    CoockedBy: "Mr. cook",
    rating: "1.09k",
  },
  {
    id: "005",
    Chicken_item: "Fried chicken",
    weight: "1.6kg",
    price: "$800",
    img: "./5.jpeg",
    CoockedBy: "Sanjeev kapoor",
    rating: "6.4k",
  },
];
